server:
  port: 8070
spring:
  application:
    name: batch
  profiles:
    active: dev
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false