server:
  port: 8071
spring:
  application:
    name: batch
  profiles:
    active: dev
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  main:
    allow-bean-definition-overriding: true